@startuml
interface Servicios {
    + pasear(): void
    + alimentar(): void
    + bañar(): void
}


class Animal { 
    + nombre: String
    + edad: int
}

class Perro {
    + raza: String
}

class Gato {
    + color: String
}

class Lagarto {
    + tamaño: String
}

class Tienda {
    - productos: List<Producto>
    + vender(producto: Producto): void
}

class Producto {
    + nombre: String
    + precio: float
}

class champu {
    
}

class comida {

}

class correa {

}
class Cliente{
    + nombre: String
}

Tienda ..> Servicios
Cliente --|> Tienda 
Tienda *-- Producto 
Tienda o-- Animal 
Animal <|-- Perro
Animal <|-- Gato
Animal <|-- Lagarto

Servicios <|.. Perro
Servicios <|.. Gato
Servicios <|.. Lagarto

Producto <|-- champu
Producto <|-- comida
Producto <|-- correa

@enduml
